import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    // Generated by `convex dev`; committed, but not ours to lint.
    "convex/_generated/**",
    // The published CLI bundle. Generated by `bun run build:cli`, and it inlines
    // cheerio and undici, so linting it reports 169 problems in other people's code.
    "dist/**",
  ]),
]);

export default eslintConfig;
